name: flutter_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

#------------------- PACKAGES -------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  cupertino_icons: ^1.0.2
  dio: ^5.5.0+1
  provider: ^6.1.2
  intl: ^0.19.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  uuid: ^4.4.2

#------------------- ./ PACKAGES END -------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #------------------- LOCAL ASSETS -------------------#
  assets:
    - assets/icons/

  #------------------- LOCAL ASSETS END -------------------#

  #  fonts:
  #    - family: Schyler
  #      fonts:
  #        - asset: fonts/Schyler-Regular.ttf
  #        - asset: fonts/Schyler-Italic.ttf
  #          style: italic
  #    - family: Trajan Pro
  #      fonts:
  #        - asset: fonts/TrajanPro.ttf
  #        - asset: fonts/TrajanPro_Bold.ttf
  #          weight: 700